package com.luckytrip.luckytrip.logger

enum class Tag {
    INFO_TAG,
    EXCEPTION_TAG,
    DEFAULT_TAG,
    SERVER_API_INFORMATIONAL,
    SERVER_API_SUCCESSFUL,
    SERVER_API_REDIRECTION,
    SERVER_API_CLIENT_ERROR,
    SERVER_API_SERVER_ERROR,
    SERVER_API_UNASSIGNED
}